name: quality_wage_app
description: Quality - Daily wage tracker for light current construction company.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  excel: 4.0.6
  file_picker: ^8.1.2
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
